DROP DATABASE IF EXISTS fusion_v04_migration_test;
CREATE DATABASE fusion_v04_migration_test;

CREATE TABLE fusion_v04_migration_test.sysmon_events
(
    event_time DateTime64(3, 'UTC'),
    ingested_at DateTime64(3, 'UTC') DEFAULT now64(3),
    event_id UInt16,
    event_type LowCardinality(String),
    channel LowCardinality(String),
    provider_name LowCardinality(String),
    record_id UInt64,
    computer LowCardinality(String),
    user String,
    process_guid String,
    process_id UInt32,
    image String,
    image_loaded String,
    command_line String,
    parent_image String,
    parent_command_line String,
    powershell_script String,
    source_ip String,
    source_port UInt16,
    destination_ip String,
    destination_port UInt16,
    destination_hostname String,
    query_name String,
    query_status String,
    query_results String,
    target_filename String,
    target_object String,
    registry_details String,
    protocol LowCardinality(String),
    initiated UInt8,
    hashes String,
    rule_name String,
    message String,
    validation_id String,
    raw_json String,
    host_name LowCardinality(String) DEFAULT computer,
    platform LowCardinality(String) DEFAULT if(event_id > 0, 'windows', 'unknown'),
    source_type LowCardinality(String) DEFAULT if(event_id > 0, 'windows_sysmon', 'unknown'),
    event_category LowCardinality(String) DEFAULT event_type,
    event_action LowCardinality(String) DEFAULT event_type,
    event_code String DEFAULT if(event_id > 0, toString(event_id), ''),
    source_event_id String DEFAULT toString(record_id),
    user_name String DEFAULT user,
    user_id String,
    process_name String DEFAULT image,
    process_path String DEFAULT image,
    parent_process_name String DEFAULT parent_image,
    parent_process_id UInt32,
    service_name String,
    outcome LowCardinality(String),
    severity LowCardinality(String)
)
ENGINE = MergeTree
ORDER BY (event_type, event_time, computer, event_id);

INSERT INTO fusion_v04_migration_test.sysmon_events
    (event_time, event_id, event_type, channel, provider_name, record_id, computer,
     user, process_guid, process_id, image, image_loaded, command_line, parent_image,
     parent_command_line, powershell_script, source_ip, source_port, destination_ip,
     destination_port, destination_hostname, query_name, query_status, query_results,
     target_filename, target_object, registry_details, protocol, initiated, hashes,
     rule_name, message, validation_id, raw_json, host_name, platform, source_type,
     event_category, event_action, event_code, source_event_id, user_name, user_id,
     process_name, process_path, parent_process_name, parent_process_id, service_name,
     outcome, severity)
VALUES
    (now64(3), 1, 'process_create', 'Microsoft-Windows-Sysmon/Operational',
     'Microsoft-Windows-Sysmon', 4001, 'V03-WINDOWS', '', '', 100, 'C:\\Windows\\System32\\cmd.exe',
     '', 'cmd.exe /c ver', '', '', '', '', 0, '', 0, '', '', '', '', '', '', '', '', 0,
     '', '', '', 'v04-migration-windows', '{"version":"0.3","platform":"windows"}',
     'V03-WINDOWS', 'windows', 'windows_sysmon', 'process', 'process_create', '1', '4001',
     '', '', 'cmd.exe', 'C:\\Windows\\System32\\cmd.exe', '', 0, '', 'unknown', 'info'),
    (now64(3), 0, 'process_execute', 'auditd', 'auditd', 5001, 'v03-linux', '', '', 200,
     '/usr/bin/id', '', '/usr/bin/id', '', '', '', '', 0, '', 0, '', '', '', '', '', '', '',
     '', 0, '', '', 'type=SYSCALL', 'v04-migration-linux', '{"version":"0.3","platform":"linux"}',
     'v03-linux', 'linux', 'linux_auditd', 'process', 'process_execute', 'SYSCALL', '5001',
     'fusion', '1000', 'id', '/usr/bin/id', '', 1, '', 'success', 'info');
