CREATE DATABASE IF NOT EXISTS fusion;

CREATE TABLE IF NOT EXISTS fusion.sysmon_events
(
    event_time DateTime64(3, 'UTC'),
    ingested_at DateTime64(3, 'UTC') DEFAULT now64(3),
    event_id UInt16,
    event_type LowCardinality(String),
    channel LowCardinality(String),
    provider_name LowCardinality(String),
    record_id UInt64,
    computer LowCardinality(String),
    user String,
    process_guid String,
    process_id UInt32,
    image String,
    image_loaded String,
    command_line String,
    parent_image String,
    parent_command_line String,
    powershell_script String,
    source_ip String,
    source_port UInt16,
    destination_ip String,
    destination_port UInt16,
    destination_hostname String,
    query_name String,
    query_status String,
    query_results String,
    target_filename String,
    target_object String,
    registry_details String,
    protocol LowCardinality(String),
    initiated UInt8,
    hashes String,
    rule_name String,
    message String,
    validation_id String,
    raw_json String,
    host_name LowCardinality(String) DEFAULT computer,
    platform LowCardinality(String) DEFAULT if(event_id > 0, 'windows', 'unknown'),
    source_type LowCardinality(String) DEFAULT if(event_id > 0, 'windows_sysmon', 'unknown'),
    event_category LowCardinality(String) DEFAULT event_type,
    event_action LowCardinality(String) DEFAULT event_type,
    event_code String DEFAULT if(event_id > 0, toString(event_id), ''),
    source_event_id String DEFAULT toString(record_id),
    user_name String DEFAULT user,
    user_id String,
    process_name String DEFAULT image,
    process_path String DEFAULT image,
    parent_process_name String DEFAULT parent_image,
    parent_process_id UInt32,
    service_name String,
    outcome LowCardinality(String),
    severity LowCardinality(String),
    device_name String DEFAULT host_name,
    vendor LowCardinality(String) DEFAULT if(platform = 'windows', 'Microsoft', if(platform = 'linux', 'Fusion', 'generic')),
    product LowCardinality(String) DEFAULT if(platform = 'windows', 'Sysmon', if(platform = 'linux', 'Linux', '')),
    event_kind LowCardinality(String) DEFAULT 'event',
    ingestion_protocol LowCardinality(String) DEFAULT if(source_type != '', 'http', ''),
    ingestion_path String DEFAULT if(platform = 'windows', '/sysmon', if(platform = 'linux', '/linux', '')),
    source_address String,
    original_format LowCardinality(String) DEFAULT if(platform IN ('windows', 'linux'), 'json', ''),
    network_direction LowCardinality(String),
    rule_id String,
    signature String,
    signature_id String,
    url String,
    domain String,
    syslog_facility LowCardinality(String),
    syslog_application String,
    INDEX image_token_idx lower(image) TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 4,
    INDEX command_token_idx lower(command_line) TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 4,
    INDEX destination_ip_idx destination_ip TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX query_name_idx lower(query_name) TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 4,
    INDEX target_filename_idx lower(target_filename) TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 4,
    INDEX process_path_token_idx lower(process_path) TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 4,
    INDEX source_type_set_idx source_type TYPE set(100) GRANULARITY 4,
    INDEX vendor_product_set_idx (vendor, product) TYPE set(250) GRANULARITY 4,
    INDEX source_address_idx source_address TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX domain_token_idx lower(domain) TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 4,
    INDEX signature_token_idx lower(signature) TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_time)
ORDER BY (event_type, event_time, computer, event_id)
TTL event_time + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 8192;
